	charmap " ",  $7f
	charmap "!",  $e7
	charmap "#",  $54
	charmap "'",  $e0
	charmap "'d", $bb
	charmap "'l", $bc
	charmap "'m", $e5
	charmap "'r", $e4
	charmap "'s", $bd
	charmap "'t", $be
	charmap "'v", $bf
	charmap "(",  $9a
	charmap ")",  $9b
	charmap ",",  $f4
	charmap "-",  $e3
	charmap ".",  $e8
	charmap "/",  $f3
	charmap "0",  $f6
	charmap "1",  $f7
	charmap "2",  $f8
	charmap "3",  $f9
	charmap "4",  $fa
	charmap "5",  $fb
	charmap "6",  $fc
	charmap "7",  $fd
	charmap "8",  $fe
	charmap "9",  $ff
	charmap ":",  $9c
	charmap ";",  $9d
	charmap "?",  $e6
	charmap "@",  $50
	charmap "A",  $80
	charmap "B",  $81
	charmap "C",  $82
	charmap "D",  $83
	charmap "E",  $84
	charmap "F",  $85
	charmap "G",  $86
	charmap "H",  $87
	charmap "I",  $88
	charmap "J",  $89
	charmap "K",  $8a
	charmap "L",  $8b
	charmap "M",  $8c
	charmap "N",  $8d
	charmap "O",  $8e
	charmap "P",  $8f
	charmap "Q",  $90
	charmap "R",  $91
	charmap "S",  $92
	charmap "T",  $93
	charmap "U",  $94
	charmap "V",  $95
	charmap "W",  $96
	charmap "X",  $97
	charmap "Y",  $98
	charmap "Z",  $99
	charmap "[",  $9e
	charmap "]",  $9f
	charmap "a",  $a0
	charmap "b",  $a1
	charmap "c",  $a2
	charmap "d",  $a3
	charmap "e",  $a4
	charmap "f",  $a5
	charmap "g",  $a6
	charmap "h",  $a7
	charmap "i",  $a8
	charmap "j",  $a9
	charmap "k",  $aa
	charmap "l",  $ab
	charmap "m",  $ac
	charmap "n",  $ad
	charmap "o",  $ae
	charmap "p",  $af
	charmap "q",  $b0
	charmap "r",  $b1
	charmap "s",  $b2
	charmap "t",  $b3
	charmap "u",  $b4
	charmap "v",  $b5
	charmap "w",  $b6
	charmap "x",  $b7
	charmap "y",  $b8
	charmap "z",  $b9
	charmap "¥",  $f0
	charmap "×",  $f1
	charmap "é",  $ba
	charmap "…",  $75
	charmap "№",  $74
	charmap "─",  $7a
	charmap "│",  $7c
	charmap "┌",  $79
	charmap "┐",  $7b
	charmap "└",  $7d
	charmap "┘",  $7e
	charmap "▶",  $ed
	charmap "♀",  $f5
	charmap "♂",  $ef

	charmap "あ", $b1
	charmap "い", $b2
	charmap "う", $b3
	charmap "え", $b4
	charmap "お", $b5
	charmap "か", $b6
	charmap "が", $26
	charmap "き", $b7
	charmap "ぎ", $27
	charmap "く", $b8
	charmap "ぐ", $28
	charmap "け", $b9
	charmap "げ", $29
	charmap "こ", $ba
	charmap "ご", $2a
	charmap "さ", $bb
	charmap "ざ", $2b
	charmap "し", $bc
	charmap "じ", $2c
	charmap "す", $bd
	charmap "ず", $2d
	charmap "せ", $be
	charmap "ぜ", $2e
	charmap "そ", $bf
	charmap "ぞ", $2f
	charmap "た", $c0
	charmap "だ", $30
	charmap "ち", $c1
	charmap "ぢ", $31
	charmap "っ", $df
	charmap "つ", $c2
	charmap "づ", $32
	charmap "て", $c3
	charmap "で", $33
	charmap "と", $c4
	charmap "ど", $34
	charmap "な", $c5
	charmap "に", $c6
	charmap "ぬ", $c7
	charmap "ね", $c8
	charmap "の", $c9
	charmap "は", $ca
	charmap "ば", $3a
	charmap "ぱ", $44
	charmap "ひ", $cb
	charmap "び", $3b
	charmap "ぴ", $45
	charmap "ふ", $cc
	charmap "ぶ", $3c
	charmap "ぷ", $46
	charmap "へ", $cd
	charmap "べ", $3d
	charmap "ぺ", $47
	charmap "ほ", $ce
	charmap "ぼ", $3e
	charmap "ぽ", $48
	charmap "ま", $cf
	charmap "み", $d0
	charmap "む", $d1
	charmap "め", $d2
	charmap "も", $d3
	charmap "ゃ", $e0
	charmap "や", $d4
	charmap "ゅ", $e1
	charmap "ゆ", $d5
	charmap "ょ", $e2
	charmap "よ", $d6
	charmap "ら", $d7
	charmap "り", $d8
	charmap "る", $d9
	charmap "れ", $da
	charmap "ろ", $db
	charmap "わ", $dc
	charmap "を", $dd
	charmap "ん", $de
	charmap "ア", $80
	charmap "ィ", $b0
	charmap "イ", $81
	charmap "ウ", $82
	charmap "エ", $83
	charmap "ォ", $84
	charmap "カ", $85
	charmap "ガ", $05
	charmap "キ", $86
	charmap "ギ", $06
	charmap "ク", $87
	charmap "グ", $07
	charmap "ケ", $88
	charmap "ゲ", $08
	charmap "コ", $89
	charmap "ゴ", $09
	charmap "サ", $8a
	charmap "ザ", $0a
	charmap "シ", $8b
	charmap "ジ", $0b
	charmap "ス", $8c
	charmap "ズ", $0c
	charmap "セ", $8d
	charmap "ゼ", $0d
	charmap "ソ", $8e
	charmap "ゾ", $0e
	charmap "タ", $8f
	charmap "ダ", $0f
	charmap "チ", $90
	charmap "ヂ", $10
	charmap "ッ", $ac
	charmap "ツ", $91
	charmap "ヅ", $11
	charmap "テ", $92
	charmap "デ", $12
	charmap "ト", $93
	charmap "ド", $13
	charmap "ナ", $94
	charmap "ニ", $95
	charmap "ヌ", $96
	charmap "ネ", $97
	charmap "ノ", $98
	charmap "ハ", $99
	charmap "バ", $19
	charmap "パ", $40
	charmap "ヒ", $9a
	charmap "ビ", $1a
	charmap "ピ", $41
	charmap "フ", $9b
	charmap "ブ", $1b
	charmap "プ", $42
	charmap "ホ", $9c
	charmap "ボ", $1c
	charmap "ポ", $43
	charmap "マ", $9d
	charmap "ミ", $9e
	charmap "ム", $9f
	charmap "メ", $a0
	charmap "モ", $a1
	charmap "ャ", $ad
	charmap "ヤ", $a2
	charmap "ュ", $ae
	charmap "ユ", $a3
	charmap "ョ", $af
	charmap "ヨ", $a4
	charmap "ラ", $a5
	charmap "ル", $a6
	charmap "レ", $a7
	charmap "ロ", $a8
	charmap "ワ", $a9
	charmap "ヲ", $aa
	charmap "ン", $ab
	charmap "ー", $e3

